---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault 
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: vault.sugarcrm.io
    http:
      paths:
      - path: /
        backend:
          serviceName: vault-lb
          servicePort: 8200
