apiVersion: batch/v1
kind: Job
metadata:
  name: consul-agent-token
spec:
  template:
    metadata:
      name: consul-agent-token
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 30
      volumes:
        - name: payload
          configMap:
            name: consul-agent-token-payload
      containers:
        - name: curl
          volumeMounts:
            - name: payload
              mountPath: /tmp/payload
          image: consul:0.8.1
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              /usr/bin/curl \
                --data @/tmp/payload/agent-token-payload.json \
                --request PUT \
                http://consul-0.consul.$(NAMESPACE).svc.cluster.local:8500/v1/acl/create?token=$(CONSUL_MASTER_KEY)
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: consul-tokens
                  key: master-token
